from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType


class PineRuntimeError(RuntimeError):
    """Stable-code runtime diagnostic.

    ``details`` is deliberately detached and read-only so callers cannot mutate
    evidence after the error has been raised.
    """

    def __init__(
        self,
        message: str,
        *,
        code: str = "PL1000",
        details: Mapping[str, object] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.details = MappingProxyType(dict(details or {}))


PL_RUNTIME_STATE_TRANSITION = "PL1100"
PL_RUNTIME_CONTEXT_REQUIRED = "PL1001"
PL_RUNTIME_VERSION_UNSUPPORTED = "PL1002"
PL_RUNTIME_TRANSACTION_CLOSED = "PL1101"
PL_RUNTIME_TRANSACTION_ACTIVE = "PL1102"
PL_RUNTIME_SEQUENCE = "PL1103"
PL_SERIES_HISTORY = "PL1200"
PL_STATE_SLOT = "PL1201"
PL_VALUE_BOOL = "PL1300"
PL_VALUE_DIVISION = "PL1301"
PL_VALUE_TYPE = "PL1302"
PL_VALUE_DOMAIN = "PL1303"
PL_STRING_FORMAT = "PL1304"
PL_TA_KERNEL = "PL1400"
PL_TA_STATE = "PL1401"
PL_REQUEST_PROVIDER = "PL1500"
PL_REQUEST_DATA = "PL1501"
PL_REQUEST_IDENTITY = "PL1502"
PL_REQUEST_DISCOVERY = "PL1503"
PL_REQUEST_POLICY = "PL1504"
PL_REQUEST_ALIGNMENT = "PL1505"
PL_REQUEST_RESULT_SHAPE = "PL1506"
PL_REQUEST_INVALID_SYMBOL = "PL1507"
PL_REQUEST_UNAVAILABLE = "PL1508"
PL_REQUEST_COVERAGE = "PL1509"
PL_REQUEST_TRANSPORT = "PL1510"
PL_REQUEST_REVISION = "PL1511"
PL_REQUEST_NESTED = "PL1512"
PL_REQUEST_CACHE = "PL1513"
PL_INPUT_INVALID = "PL1600"
PL_TIMEZONE_INVALID = "PL1601"
PL_SESSION_INVALID = "PL1602"
PL_METADATA_INVALID = "PL1603"
PL_REFERENCE_INVALID = "PL1610"
PL_REFERENCE_BOUNDS = "PL1611"
PL_REFERENCE_TYPE = "PL1612"
PL_VISUAL_LIMIT = "PL1620"
PL_ALERT_LIMIT = "PL1621"
PL_DELEGATED_HANDLER_UNAVAILABLE = "PL1700"
PL_DELEGATED_TARGET = "PL1701"
PL_DELEGATED_INVOCATION = "PL1702"
PL_DELEGATED_HANDLER_FAILURE = "PL1703"
PL_CHECKPOINT_INVALID = "PL1800"
PL_CHECKPOINT_IDENTITY = "PL1801"
PL_RESOURCE_LIMIT = "PL1900"
PL_ABI_MANIFEST = "PL2000"
PL_ABI_TARGET = "PL2001"
